import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to a nextjs rewrite test
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>next.config.js</code>
        </p>

        <ul>
            <li>
                <Link href="/foo-bar">
                <a>Foo Bar (always works)</a>
                </Link>
                <ul>
                  <li>Expected - render static page</li>
                  <li>Actual - renders static page</li>
                  <li>Result - works as expected</li>
                </ul>
            </li>
            <li>
                <Link href="/boo/far">
                <a>Boo Far (breaks when catch all rewrites are enabled)</a>
                </Link>
                <ul>
                  <li>Expected - render static page</li>
                  <li>Actual - returns custom 404</li>
                  <li className={styles.error}>Result - we get a custom 404 instead of a page</li>
                </ul>
            </li>
            <li>
                <Link href="/foo/bar">
                <a>Redirect to foo-bar (works when rewrites are enabled)</a>
                </Link>
                <ul>
                  <li>Expected - redirect to homepage</li>
                  <li>Actual - redirects to homepage</li>
                  <li>Result - works as expected</li>
                </ul>
            </li>
            <li>
                <Link href="/not-a-real-page">
                  <a>Not a real page - throws a 404 (green text when rewrites are enabled</a>
                </Link>
                <ul>
                  <li>Expected - display custom 404</li>
                  <li>Actual - displays custom 404</li>
                  <li>Result - works as expected</li>
                </ul>
            </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
